# Generated by Django 5.0.2 on 2024-03-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_module_1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timehistory",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
