# Generated by Django 5.0.2 on 2024-03-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_module_1", "0002_timehistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timehistory",
            name="time_change_request",
            field=models.TextField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
            ),
        ),
    ]
