# Generated by Django 5.0.2 on 2024-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_module_1", "0003_alter_timehistory_time_change_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("company", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "total_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_changes_requested", models.IntegerField(default=0)),
                ("project_notes", models.TextField(blank=True)),
                ("project_requirements", models.TextField()),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ongoing", "Ongoing"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("Travel", "Travel"),
                            ("Supplies", "Supplies"),
                            ("Equipment", "Equipment"),
                            ("Services", "Services"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("project_manager", models.CharField(max_length=100)),
                ("project_description", models.TextField()),
                (
                    "budget_allocated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("actual_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0, help_text="Progress in percentage"
                    ),
                ),
                ("issues", models.TextField(blank=True, null=True)),
                ("accomplishments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
