# Generated by Django 5.0.2 on 2024-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answers", models.JSONField()),
                ("correct_answer", models.TextField()),
                ("category", models.TextField()),
                ("difficulty", models.TextField()),
            ],
        ),
    ]
