# Generated by Django 5.0.2 on 2024-02-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_for_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Careers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("mail", models.EmailField(max_length=254)),
                ("contactnumber", models.IntegerField()),
                ("category", models.TextField()),
                ("experience", models.IntegerField()),
                ("cv", models.FileField(upload_to="")),
                ("status", models.TextField(default="pending")),
                ("appliedto", models.TextField()),
                ("teststatus", models.TextField(default="pending")),
                ("testid", models.TextField()),
            ],
        ),
    ]
