# Generated by Django 5.0.2 on 2024-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_for_users", "0002_careers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careers",
            name="testid",
            field=models.TextField(unique=True),
        ),
    ]
