# Generated by Django 5.0.2 on 2024-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_for_users", "0003_alter_careers_testid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careers",
            name="contactnumber",
            field=models.BigIntegerField(),
        ),
    ]
