# Generated by Django 5.0.2 on 2024-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_for_users", "0004_alter_careers_contactnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careers",
            name="appliedto",
            field=models.TextField(default="RAMO"),
        ),
        migrations.AlterField(
            model_name="careers",
            name="cv",
            field=models.FileField(upload_to="cv_files/"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="difficulty",
            field=models.TextField(default="null"),
        ),
    ]
